### ISSUE TITLE
Add a requirements file

### ISSUE THREAD

**Issue by itsrifat** [mtpain/vwplatform#12]
It will be good to have a requirements file for the application so that its easy to install the requirements easily !

**Comment by mt-digital** [comment]
@itsrifat added requirements file and included some other dependencies. Try it out and if it works, close this issue. Thanks!

**Comment by itsrifat** [comment]
I still couldn't get it running. There are some duplicate requirements in the file:
- python-dateutil
- nose
- SQLAlchemy

After commenting out these duplicates having error on installing couple of packages thorugh requirements.txt which are:
- GDAL
- lxml

So I tried installing these two manually. After that running `python models.py runserver` from the app directory is giving import  error. The error looks like this:

```
ImportError: cannot import name current_app
```

Even though looks like flask is installed though requirements.txt Any thoughts?

**Comment by mt-digital** [comment]
I made a mistake (corrected now) in the README, it should be `python manage.py runserver`, run from the root directorty of the project.

**Comment by itsrifat** [comment]
Now getting this:

`AssertionError: Config file /home/escenic/vwplatform/default.conf does not exist!`

**Comment by mt-digital** [comment]
ok, sorry for not including this part in the README. Thanks again for working through this.

You need to edit `default.conf.template` and fill out user name, password, and virtual watershed address. You also need to write in the path to two directories that start with `/PATH/TO/EDIT` or something like that. Then save the edited file as `default.conf`. Don't add your `default.conf` to be tracked by git!

**Comment by mt-digital** [comment]
email me if you need a reminder for the user name and password. They are the ones we got in nm.

**Comment by itsrifat** [comment]
I didn't quite get what do you mean by editing `default.conf.template` ? Where do I need to edit that?

**Comment by mt-digital** [comment]
sorry, it should have been included, but it wasn't there.

I just pushed an update that includes `default.conf.template` in the root directory and two template files in the `resources` directory. There are two paths `PATH/TO/VWPLATFORM` where you need to substitute in the path to the project.

**Comment by mt-digital** [comment]
This is definitely overly complicated, but I haven't had time to improve it.

**Comment by itsrifat** [comment]
Can you also remove the duplicates from the requirements.txt file? And it would be nice to see how to install GDAL and lxml through requirements.txt. if you change and push I can check again if the requiremtns.txt is working properly

**Comment by mt-digital** [comment]
OK, done.

**Comment by mt-digital** [comment]
This seems to be working now, closing.
