### ISSUE TITLE
format "Share" page

### ISSUE THREAD

**Issue by mt-digital** [mtpain/vwplatform#15]
part of the work in progress, but we need to make sure the Share page is formatted like the rest.

**Comment by itsrifat** [comment]
I can't actually access the share page, Its asking for email confirmation after login. How do I temporarily disable the email confirmation feature or add email server configs?

**Comment by mt-digital** [comment]
OK. Even though it's slick and a little more secure with the email confirmation it is creating problems (see #9, #10). So to close #9 and to make this easier, I'm going to disable email confirmation until we have time to address its issues. I'll create a new feature issue with email confirmation as the feature.

**Comment by mt-digital** [comment]
tackled with #16
