### ISSUE TITLE
redesign dataset view for a modelrun

### ISSUE THREAD

**Issue by mt-digital** [mtpain/vwplatform#25]
The `share/` route currently shows the modelruns currently tracked in the `resources` table in the db. On clicking "Add files to this resource" the user is shown a form to upload files in the `share/files/{model_run_uuid}`. 

In addition to the option to upload files in this view, the user should also be presented with a list of current datasets that have been uploaded and inserted to the VW.  Bootstrap lists should be good: http://getbootstrap.com/components/#list-group-badges

You could use the badge that says "Download" to provide the user the opportunity to download the file. 

The list should look something like this:

| File Name | Watershed Name | description | Services and Download |
| --- | --- | --- | --- |
| "rc_stations.csv" | Reynolds Creek | Weather station data 1995-2001 | <a href="#">wcs</a> <a href="#">wms</a>  <a href="#">Download</a> |

**Comment by lipalath-ms** [comment]
Should the list contain all the datasets available from VW? (under all model runs)

**Comment by mt-digital** [comment]
no, only the model run that the user is adding files to

**Comment by lisapalathingal** [comment]
Ok, correct me I am wrong: List should be displayed in this page, right?[image:
Inline image 1]

**Comment by mt-digital** [comment]
One change above: I've changed "Download Link" to "Downloads/Services". Please put badges for wcs and wms if they are available. No badge if not.
