### ISSUE TITLE
VW  bounding box issue

### ISSUE THREAD

**Issue by ChaseCarthen** [mtpain/vwplatform#36]
The bounding box within the virtual watershed metadata is used for the WMS service.
Consequently if the bounding box within the metadata does not match the dataset's internal bounding box there will be issues in the visualization. 

I don't know how this will be impacted by the netcdf.

**Comment by mt-digital** [comment]
OK, thanks, Chase. I am out of town the rest of this week. It would probably be good for you to check in one-on-one with the UNM guys to chat about NetCDF and bring up this question.

**Comment by ChaseCarthen** [comment]
I never gave an example why this is a problem, so please let me explain here:
I am using the model_run_uuid de781fc8-d829-4c2a-bd40-ee6e7120814e and one of its datasets as an example

Here is the json bounding box: [-120.01, 31.17, -102.66, 49.13]

http://vwp-dev.unm.edu//apps/vwp/search/datasets.json?model_run_uuid=de781fc8-d829-4c2a-bd40-ee6e7120814e

Here is the wms bounding box: LatLonBoundingBox minx="-120.01" miny="31.17" maxx="-102.66" maxy="49.13"
http://vwp-dev.unm.edu/apps/vwp/datasets/a9056f19-39f2-4bb5-bdce-d3993e105472/services/ogc/wms?SERVICE=wms&REQUEST=GetCapabilities&VERSION=1.1.1

Here is wcs bounding box: 
ows:LowerCorner39.028019 -114.368852/ows:LowerCorner
ows:UpperCorner39.139274 -114.323106/ows:UpperCorner
http://vwp-dev.unm.edu/apps/vwp/datasets/a9056f19-39f2-4bb5-bdce-d3993e105472/services/ogc/wcs?SERVICE=wcs&REQUEST=GetCapabilities&VERSION=1.1.2

As you can see the wms bounding box is based off of the bounding box passed to the json, but the wcs request is based off of the actual data's geospatial information. 

WMS does not use the actual bounding box contained within the actual data.
This can be issue in the case of landsat photos where wms is a key factor for visualizing the landsat. If the bounding box is incorrect in the WMS, then it will be visualized incorrectly.

**Comment by ChaseCarthen** [comment]
Should this be a fix on the server side?

**Comment by mt-digital** [comment]
Yes, I think this is a server-side issue, so I'll close this. The fix then should be to just use the bounding box from the data, right?

**Comment by ChaseCarthen** [comment]
Yes that would be correct.

**Comment by mt-digital** [comment]
Thanks for reopening, this is my top priority. Hope to have it done today.
