### ISSUE TITLE
Upload files

### ISSUE THREAD

**Issue by ruiwu1990** [mtpain/vwplatform#37]
I am still new... So this may sound stupid. Where should I store the users' uploaded files? Have you guys done something similar to process users' uploaded files?

**Comment by mt-digital** [comment]
Lisa has done this. When using the app, go to the `/share` tab, then you'll see the first screenshot below. Click on a green button that's attached to a resource description and you'll be taken to the second screenshot where you can upload files to the virtual watershed.

Please get in touch with Lisa if you need more info on how this works.

![share_view](https://cloud.githubusercontent.com/assets/2425472/8368116/1e8cd8f6-1b5b-11e5-9e70-24f6ad120d9b.png)

![upload_view](https://cloud.githubusercontent.com/assets/2425472/8368117/1e8d7374-1b5b-11e5-9545-edefbb27281b.png)
