### ISSUE TITLE
histograms and histogram movies for netcdf files

### ISSUE THREAD

**Issue by mt-digital** [mtpain/vwplatform#44]
Scientists would like to be able to spot check grids that are being generated from the ISU gridding tool. One tool that was mentioned was a histogram. Please use a modern web visualization tool (D3, etc.) to do this. Below is an example of what I mean by "histogram of a grid" using numpy and matplotlib.

Checking the histogram allows a scientist to instantly see if any values are extremely wrong in a way they couldn't do otherwise. For example, if there are temperatures at 150 deg C, these might not be visible on a map if they were scattered about an image, but they could have a huge impact on the accuracy of a model.  The histogram makes extreme values obvious by stretching the x-axis to unreasonable extremes.

Use this input netcdf for isnobal from the Dry Creek Watershed Kormos data: http://vwp-dev.unm.edu/apps/vwp/datasets/213b010b-1fd7-4b54-8c96-cfbcf6ff42c2/twoweek_inputs_with_zlib.nc.original.nc retrieved from https://vw.northwestknowledge.net/share/files/37163f50-2007-4d1c-9208-501f2d2db6f5

``` bash
wget -O twoweek_inputs.nc http://vwp-dev.unm.edu/apps/vwp/datasets/213b010b-1fd7-4b54-8c96-cfbcf6ff42c2/twoweek_inputs_with_zlib.nc.original.nc
```

``` python
import matplotlib.pyplot as plt
from netCDF4 import Dataset

nc = Dataset('twoweek_inputs.nc')
ilw = nc.variables['I_lw']

plt.hist(ilw[0].flatten())
plt.xlabel(ilw.units)
plt.ylabel('Pixel counts')
plt.title('Pixel count of ' + ilw.standard_name + ' for timestep 0')
```

![example_histogram](https://cloud.githubusercontent.com/assets/2425472/9412014/58d52068-47de-11e5-991a-5567dd4d64ce.png)

As you can see on the screenshot of the example histogram, the units go on the x-axis and the y-axis counts how many pixels in the image fall within the bin delineated by the width of the bar.  Also note how you can use the netCDF metadata itself to help you annotate the plot. Please do that as well.

**Comment by ruiwu1990** [comment]
En, I finished the bar graph (I somehow prefer this name). The workflow is similar to draw a line chart. 
1) upload a netcdf file
2) choose a variable to visualize
3) choose one dimension of the chosen variable to visualize with bar chart (bar chart contains the chosen dimension and variable itself, e.g. the user chooses 'time' of variable 'temperature')
4) specify other dimensions (e.g. the user chooses 'time' and he needs to specify other dimensions: northing and easting)
5) visualize data with bar chart as the following screenshot:

![screenshot from 2015-08-24 16 42 03](https://cloud.githubusercontent.com/assets/8552440/9455332/195ddd64-4a7f-11e5-80c1-cce5e213267e.png)

I can add some animation to the bar chart, however, there are too many numbers (400 for this example), it will slow the visualization.

P.S.: I found my part stuck when it visualized 'I_lw' with 2D map. I will debug it.

**Comment by mt-digital** [comment]
This is a great start.

However, there is a difference between a "bar chart" and a "histogram". A histogram has many less "bins", or bars, than the total number of pixels. Please read up on the difference between bar charts and histograms.

Plus like I explained, the variable (in this case watts per meter squared) will be on the x axis and the number of pixels whose value falls within a bin is on the y axis. Please take a close look at the example I gave you and read the documentation on matplotlib's histogram function.

As always give me a call if you'd like to talk about this in more detail.

**Comment by ruiwu1990** [comment]
Oh... Here is the prototype screenshot:

![screenshot from 2015-08-25 18 06 49](https://cloud.githubusercontent.com/assets/8552440/9483373/5c851f1e-4b54-11e5-98eb-b18b746f440f.png)

The workflow is :

1) upload a netcdf file
2) choose a variable to visualize
3) choose one dimension of the chosen variable to visualize with histogram 
4) input how many sections to separate (the screenshot uses 10 sections)
5) visualize data with histogram

**Comment by ruiwu1990** [comment]
Update and Question:

I redesign the histogram (add a line chart and add x labels). When users hover the line chart a tab will appear. Here is a screenshot:

![screenshot from 2015-08-26 13 02 59](https://cloud.githubusercontent.com/assets/8552440/9504741/1637cf8a-4bf3-11e5-8077-24efa2b87e6e.png)

Question:

How can I grab data in one dimensional array in a general way if the time dimension is not the first dimension? This means I cannot obtain data using this: 

```
ilw = nc.variables['I_lw']
data_array = ilw[0].flatten()
```

e.g. If 'time' is second dimension and we have 4 dimension in total. Then I need to set up a loop to combine all ilw[m][0].flatten(). Could you please give me some suggestions?

**Comment by ruiwu1990** [comment]
Update: Add a button named 'Display Next Time Distribution'. When users click this button, the system will display data frequency distribution of next timestamp. Here is a screenshot:

![screenshot from 2015-09-02 12 30 07](https://cloud.githubusercontent.com/assets/8552440/9642079/15561078-516f-11e5-9094-905ba2fb988f.png)

I also add titles for the graph, x axis tile and y axis title. I found some bugs of this part. I will work on debugging and create an interface of this part for Chase in the following days.

**Comment by ruiwu1990** [comment]
Update:
1) Fix a bug: when users click on bar chart, weird things will happen 
2) create an interface for Chase
3) add play and pause button, if users click 'play' button, the histogram will be updated every 1 second; if users click 'pause' button, the update process will be stopped.

![screenshot from 2015-09-08 11 36 09](https://cloud.githubusercontent.com/assets/8552440/9743995/24480966-561e-11e5-8864-180fc3328568.png)

**Comment by ruiwu1990** [comment]
Found a bug. The program runs forever for big file such as twoweek_inputs_with_zlib.nc. The reason is that for each time step for 'I_lw' takes around 0.8 seconds to change 2D array in 1D array, order the 1D array, slice the 1D array, give each slice name, put the slice number and slice name into a class. And for the twoweek_inputs_with_zlib.nc, it has 400 time steps.

Please tell me your opinions about this idea: I will use two threads in the front-end javascript. One thread visualizes current 10 time steps data, another thread obtain next 10 time steps data.

**Comment by ruiwu1990** [comment]
I used the following code to obtain variable informations

```
    for count in range(0,element_num):
        # initialize these array and lists
        # section_results_number records how many elements are in each section
        section_results_number = []
        # tab_name_list records names of each section
        tab_name_list = []
       # convert 2D array into 1D array
        aim_array = temp_dim_handle[count].flatten()
        units = ''
        standard_name = ''
        # the details of this function is listed in the next part
        util.sort_section_number(aim_array, section_num, section_results_number, tab_name_list)
        # .ncattrs() is used to list all the attributes of the chosen variable
        if  'units' in temp_dim_handle.ncattrs():
            units = temp_dim_handle.units
        if  'standard_name' in temp_dim_handle.ncattrs():
            standard_name = temp_dim_handle.standard_name
        # you can find detail information of FrequenceDistributionInformation in the next part
        temp_object = FrequenceDistributionInformation(aim_array, section_results_number, tab_name_list, units, standard_name)
        class_information_list.append(temp_object)
```

The code of function 'sort_section_number' is listed below:

```
# This function is used to sort a numpy array and 
# return a 1D list with m numbers, each number means 
# the number of array elements in the section from min+x*(max-min)/section_number
# to min+(x+1)(max-min)/section_number, this function also returns the tab name list
def sort_section_number(numpy_input_array=[], section_number=1, section_results_number=[],tab_name_list=[]):
    ordered_array = np.sort(numpy_input_array)
    max_value = ordered_array[numpy_input_array.size-1]
    min_value = ordered_array[0]
    interval_value = (max_value-min_value)/section_number
    # this is used to record elements section numbers
    temp_results_number = [0]*section_number
    for item in ordered_array:
        for count in range(0,section_number):
            # record the number of elements in each section
            if item>=min_value+count*interval_value and item<=min_value+(count+1)*interval_value:
                temp_results_number[count] = temp_results_number[count] + 1
    # create tab name
    for count in range(0,section_number):
        # 2 digits precisions for float
        bound_floor = "%.2f" % (min_value+count*interval_value)
        bound_cell = "%.2f" % (min_value+(count+1)*interval_value)
        tab_name_list.append(str(bound_floor)+' to '+str(bound_cell))
    # push results into section_results_number
    for item in temp_results_number:
        section_results_number.append(item)
```

Here is the FrequenceDistributionInformation details:

```
# this class is used for histograms of frequence distribution visualization
class FrequenceDistributionInformation:
    data = np.array([])
    # bar chart y values
    section_results_number = []
    # bar chart x tabs
    tab_name_list = []
    title = ''
    units =''
    standard_name = ''
    def __init__(self, data_input, section_results_number_input, tab_name_list_input, units_input, standard_name_input):
        self.data = data_input
        self.section_results_number = section_results_number_input
        self.tab_name_list = tab_name_list_input
        self.units = units_input
        self.standard_name = standard_name_input
```

**Comment by ruiwu1990** [comment]
Well, I updated histogram part and loading time is much faster now and users will feel lagged if there are a lot of timestamps data. The basic idea is the system will load first 5 timestamps data. When users click 'Display Next Time Distribution' button, the system will first display next frame data and then load another frame into something like a pipe. The process is serial not parallel. You can find my updates from: https://github.com/ruiwu1990/vwplatform.git

I tried parallel.js. En my opinion is that the library is not doing things in parallel. It just fakes something like parallel. The reason for that is I tried to use two threads and one of the thread did nothing until another finished. Therefore I used serial programming. There is a problem now: while loading data, the button will not react (maybe because I used XMLHttpRequest to load data). This means users need to try a lot of times to pause the animation, after they start it.

**Comment by ruiwu1990** [comment]
Muhahaha, got helped by Moinul again. Now when the system loading data, the button will reacts better than before. I used jquery $.get to load data instead of XMLLHttpRequest to load data. 

P.S. Matthew, if you need me to do something else, please email me. Now I will improve my previous code.

**Comment by mt-digital** [comment]
Hi @ruiwu1990  I'm trying to run your latest master locally, but I'm getting the error here when I try to visualize a netcdf dataset.  Any idea what's going on?
![screen shot 2015-10-04 at 5 06 59 pm](https://cloud.githubusercontent.com/assets/2425472/10271099/69fd1d1a-6aba-11e5-9bc4-d0040f20f032.png)

**Comment by ruiwu1990** [comment]
Let me update my latest version tomorrow morning.

**Comment by ruiwu1990** [comment]
Sorry that I left my code in the lab...

**Comment by mt-digital** [comment]
Dude no problem!  Thanks for checking it out!

**Comment by ruiwu1990** [comment]
Matthew, could you please check it again? I found I forgot to update my latest part. This time histogram visualization will not be affected by the size of netcdf file.

**Comment by ruiwu1990** [comment]
Oh, here is the link of my github, just updated.
https://github.com/ruiwu1990/vwplatform.git
