### ISSUE TITLE
Unity Model Run Scene

### ISSUE THREAD

**Issue by ChaseCarthen** [mtpain/vwplatform#8]
I was thinking we could create a webpage that animates a model run on a DEM specific to that model run.

Example Use Case:
User searches for a Model Run. 

That user can then specify choose some option to visualize that particular model run in another window. 

This would require that the user's selected data is to Unity Webplayer via a javascript function, since the Unity webplayer can communicate with javascript.

**Comment by mt-digital** [comment]
In the code you'll share, is there an example of how the unity webplayer communicates via javascript?

**Comment by ChaseCarthen** [comment]
Yes I will go ahead and make any example project for you tomorrow.

**Comment by ChaseCarthen** [comment]
Here is a link that I refer to get javascript and Unity talking to each other: http://docs.unity3d.com/Manual/UnityWebPlayerandbrowsercommunication.html
